DbPath: /home/test/DB # Path to the folder containing db files, can be relative or absolute
SegSize: 67108864 # Max data segment size
MaxKeySize: 255 # Max key length
MaxValueSize: 100000 # Max value length
CacheSize: 50000 # Max number of values in the cache
CompactingInterval: 300 # The ammount of time in seconds between each compaction of the INDEX and the data segments
FlushInterval: 500 # The ammount of time in seconds between each sync on the disk

DBPort: 7321
WebPort: 1237

NetworkValidation: ".*" # Regex for allowed incoming request IP addresses

isDebug: false # Degug mode for the logger
jsonOnly: false
readOnly: false

useSSL: false # Use SSL ?
SSLCertPath: ./cert.pem # Path to the generated certification file, can be relative or absolute
SSLKeyPath: ./key.pem # Path to the generated key file, can be relative or absolute

ArchiveStoragePath: /home/test/DBArchives
ArchiveCreationDelay: 100 # In seconds
AutoArchiveSaving: true

users:
  - user: bob
    password: bob